[tox]
envlist = py{311,312,313,314}-{linux,macos,windows}

requires =
    setuptools

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
deps =
    pytest
commands =
    pytest


[testenv:dev]
basepython = python3.13
deps =
    pytest
    pytest-cov
commands =
    coverage erase
    pytest --cov=valvevmf --cov-report html

[testenv:coverage]
basepython = python3.13
deps =
    pytest
    pytest-cov
    coverage-badge
commands =
    coverage erase
    pytest --cov=valvevmf --cov-report html
    coverage-badge -fo docs/source/coverage.svg

[testenv:docs]
basepython = python3.13
deps =
    sphinx
    pytest
    pytest-cov
    coverage-badge
commands =
    coverage erase
    pytest --cov=valvevmf --cov-report html
    coverage-badge -fo docs/source/coverage.svg
    python -m sphinx docs/source/ docs/build/
